# Task 4: Fine-tuning Faster R-CNN on deblurred GoPro images

import os
import json
import time
import torch
import numpy as np
import cv2
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader
from torchvision import models, transforms
from torchvision.models.detection import FasterRCNN_ResNet50_FPN_Weights
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor

# Dataset

class DeblurDetectionDataset(Dataset):
    """
    Dataset of deblurred images with pseudo-annotations
    generated by a pretrained Faster R-CNN.
    """
    def __init__(self, image_paths, annotations, transforms=None):
        self.image_paths = image_paths
        self.annotations = annotations  # list of dicts {boxes, labels}
        self.transforms  = transforms

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_bgr = cv2.imread(self.image_paths[idx])
        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
        img_t   = torch.from_numpy(
                      img_rgb.transpose(2, 0, 1)).float() / 255.0

        ann    = self.annotations[idx]
        boxes  = torch.tensor(ann['boxes'],  dtype=torch.float32)
        labels = torch.tensor(ann['labels'], dtype=torch.int64)

        # Need at least one box
        if len(boxes) == 0:
            boxes  = torch.zeros((0, 4), dtype=torch.float32)
            labels = torch.zeros((0,),   dtype=torch.int64)

        target = {
            'boxes':    boxes,
            'labels':   labels,
            'image_id': torch.tensor([idx])
        }
        return img_t, target


def collate_fn(batch):
    return tuple(zip(*batch))

# Pseudo-annotation generator

def generate_pseudo_annotations(image_paths, model, device,
                                  threshold=0.7, max_size=640,
                                  save_path=None):
    """
    Run pretrained Faster R-CNN to generate pseudo ground-truth
    annotations for the deblurred images.
    """
    print(f"Generating pseudo-annotations for {len(image_paths)} images...")
    model.eval()
    to_tensor = transforms.ToTensor()
    annotations = []

    for i, path in enumerate(image_paths):
        img = cv2.imread(path)
        if img is None:
            annotations.append({'boxes': [], 'labels': []})
            continue

        # Resize
        h, w   = img.shape[:2]
        scale  = max_size / max(h, w)
        if scale < 1.0:
            img = cv2.resize(img, (int(w*scale), int(h*scale)))

        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        tensor  = to_tensor(img_rgb).unsqueeze(0).to(device)

        with torch.no_grad():
            out = model(tensor)[0]

        mask   = out['scores'].cpu().numpy() >= threshold
        boxes  = out['boxes'].cpu().numpy()[mask].tolist()
        labels = out['labels'].cpu().numpy()[mask].tolist()
        annotations.append({'boxes': boxes, 'labels': labels})

        if (i+1) % 50 == 0:
            print(f"  {i+1}/{len(image_paths)} annotated")

    if save_path:
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        with open(save_path, 'w') as f:
            json.dump(annotations, f)
        print(f"Annotations saved to {save_path}")

    return annotations

# Model builder

def build_finetuned_model(num_classes=91, device=None):
    """
    Load Faster R-CNN with pretrained backbone,
    replace the classification head for fine-tuning.
    """
    if device is None:
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    weights = FasterRCNN_ResNet50_FPN_Weights.DEFAULT
    model   = models.detection.fasterrcnn_resnet50_fpn(weights=weights)

    # Replace head
    in_features = model.roi_heads.box_predictor.cls_score.in_features
    model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)
    model.to(device)
    return model, device

# Training loop

def train_one_epoch(model, optimizer, dataloader, device, epoch):
    """Train for one epoch, return avg loss."""
    model.train()
    total_loss = 0.0
    n_batches  = len(dataloader)

    for i, (images, targets) in enumerate(dataloader):
        images  = [img.to(device) for img in images]
        targets = [{k: v.to(device) for k, v in t.items()}
                   for t in targets]

        loss_dict = model(images, targets)
        losses    = sum(loss_dict.values())

        optimizer.zero_grad()
        losses.backward()
        optimizer.step()

        total_loss += losses.item()
        if (i+1) % 10 == 0 or (i+1) == n_batches:
            print(f"  Epoch {epoch} [{i+1}/{n_batches}] "
                  f"loss: {losses.item():.4f}")

    return total_loss / n_batches


def train_model(model, dataloader, device,
                epochs=5, lr=0.001, log_path=None):
    """
    Full training loop with learning rate scheduler.
    Returns training log.
    """
    # Only fine-tune the detection head
    params = [p for p in model.parameters() if p.requires_grad]
    optimizer = torch.optim.SGD(
        params, lr=lr, momentum=0.9, weight_decay=0.0005)
    scheduler = torch.optim.lr_scheduler.StepLR(
        optimizer, step_size=3, gamma=0.1)

    log = {
        'epochs': [], 'losses': [], 'lr': [],
        'epoch_times': [],
        'hyperparameters': {
            'lr': lr, 'momentum': 0.9,
            'weight_decay': 0.0005,
            'epochs': epochs,
            'batch_size': dataloader.batch_size,
            'scheduler': 'StepLR(step=3, gamma=0.1)'
        }
    }

    print(f"\nStarting fine-tuning for {epochs} epochs on {device}")
    print(f"Hyperparameters: lr={lr}, momentum=0.9, "
          f"weight_decay=0.0005\n")

    for epoch in range(1, epochs+1):
        t0       = time.time()
        avg_loss = train_one_epoch(
            model, optimizer, dataloader, device, epoch)
        elapsed  = time.time() - t0
        cur_lr   = scheduler.get_last_lr()[0]
        scheduler.step()

        log['epochs'].append(epoch)
        log['losses'].append(avg_loss)
        log['lr'].append(cur_lr)
        log['epoch_times'].append(elapsed)

        print(f"Epoch {epoch}/{epochs} — "
              f"avg loss: {avg_loss:.4f} | "
              f"lr: {cur_lr:.6f} | "
              f"time: {elapsed:.1f}s\n")

    if log_path:
        os.makedirs(os.path.dirname(log_path), exist_ok=True)
        with open(log_path, 'w') as f:
            json.dump(log, f, indent=2)
        print(f"Training log saved to {log_path}")

    return log

# Visualisation

def plot_training_log(log, save_path=None):
    """Plot loss curve and learning rate schedule."""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

    ax1.plot(log['epochs'], log['losses'],
             'o-', color='#534AB7', linewidth=2)
    ax1.set_xlabel('Epoch', fontsize=12)
    ax1.set_ylabel('Avg loss', fontsize=12)
    ax1.set_title('Training loss curve', fontsize=13)
    ax1.grid(True, alpha=0.3)

    ax2.plot(log['epochs'], log['lr'],
             's-', color='#1D9E75', linewidth=2)
    ax2.set_xlabel('Epoch', fontsize=12)
    ax2.set_ylabel('Learning rate', fontsize=12)
    ax2.set_title('Learning rate schedule', fontsize=13)
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    if save_path:
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        print(f"Saved: {save_path}")
    plt.show()
    return fig

def plot_annotation_stats(annotations, save_path=None):
    """Bar chart of pseudo-annotation class distribution."""
    from collections import Counter
    COCO_CLASSES = [
        '__background__', 'person', 'bicycle', 'car', 'motorcycle',
        'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light',
        'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird',
        'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear',
        'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie',
        'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball',
        'kite', 'baseball bat', 'baseball glove', 'skateboard',
        'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup',
        'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
        'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog',
        'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant',
        'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse',
        'remote', 'keyboard', 'cell phone', 'microwave', 'oven',
        'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase',
        'scissors', 'teddy bear', 'hair drier', 'toothbrush'
    ]

    all_labels = []
    for ann in annotations:
        all_labels.extend(ann['labels'])

    counts = Counter(all_labels)
    top10  = counts.most_common(10)
    names  = [COCO_CLASSES[l] if l < len(COCO_CLASSES)
              else str(l) for l, _ in top10]
    values = [c for _, c in top10]

    fig, ax = plt.subplots(figsize=(10, 4))
    ax.bar(names, values, color='#534AB7', alpha=0.8)
    ax.set_xlabel('Class', fontsize=12)
    ax.set_ylabel('Count', fontsize=12)
    ax.set_title('Top 10 classes in pseudo-annotation dataset',
                 fontsize=13)
    plt.xticks(rotation=30, ha='right')
    ax.grid(axis='y', alpha=0.3)
    plt.tight_layout()
    if save_path:
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        print(f"Saved: {save_path}")
    plt.show()
    return fig